var foo = 1;
var bar = [
  'this should be removed by tree shaking',
  'this should be removed by tree shaking',
  'this should be removed by tree shaking',
  'this should be removed by tree shaking',
  'this should be removed by tree shaking',
  'this should be removed by tree shaking',
  'this should be removed by tree shaking',
  'this should be removed by tree shaking',
  'this should be removed by tree shaking',
  'this should be removed by tree shaking',
  'this should be removed by tree shaking',
  'this should be removed by tree shaking',
  'this should be removed by tree shaking',
  'this should be removed by tree shaking',
  'this should be removed by tree shaking',
  'this should be removed by tree shaking',
  'this should be removed by tree shaking',
  'this should be removed by tree shaking',
  'this should be removed by tree shaking',
  'this should be removed by tree shaking',
  'this should be removed by tree shaking',
  'this should be removed by tree shaking',
  'this should be removed by tree shaking',
  'this should be removed by tree shaking',
  'this should be removed by tree shaking',
  'this should be removed by tree shaking',
  'this should be removed by tree shaking',
  'this should be removed by tree shaking',
  'this should be removed by tree shaking',
  'this should be removed by tree shaking',
];

export { foo, bar };